// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Alpha_ABS","status":true,"description":"ABS \"Alpha\"","parameters":{"Enemy Dead Switch":"B","After Dead Map":"0","Cast Animation":"0","Level Up Animation":"49","Revive Animation":"45","Use default cast SE":"true","Auto loot enemies":"false","UI visibility control":"true","UI position control":"true","Gold icon index":"314","Key binding":"true","Show XP bar":"false","Dash on ABS map":"false","Allow Transfrer":"false","Force English":"false","---Control Panel Settings---":"","Follow allowed":"false","Jump allowed":"false","Rotate allowed":"false","Favorite weapons allowed":"false"}},
{"name":"CMPUTCustom","status":true,"description":"CMPUT250 Custom Code","parameters":{}},
{"name":"SRD_CollisionChecker","status":true,"description":"Allows developers to check the collision of various coordinates/directions on the map for event collision.","parameters":{}},
{"name":"TerraxLighting","status":true,"description":"v1.5.1 Creates an extra layer that darkens a map and adds lightsources!","parameters":{"Player radius":"0","Add to options":"Yes","Option menu entry":"Lighting effects","Reset Lights":"No","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Flashlight offset":"0","Screensize X":"866","Screensize Y":"630","Kill Switch":"No"}}
];
